version: '2.1'

services:
  moerae:
    image: moerae
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js