#!/bin/bash

export NODE_ENV=development

for line in $(cat ./app.env);
do
  if [ ${line:0:1} != '#' ]; then
    if [ $(echo $line | grep "\=") ]; then
      echo "[dev] - export env $line"
      export $line
    fi
  fi
done

if [ "x$1" = "xmongo" ]; then
docker run -d --name $MR_NAME-dev-mongo --rm \
  --mount type=bind,src=$MR_DEV_MONGO_DATA_PATH,dst=/data/db \
  -e MONGO_INITDB_ROOT_USERNAME=$MR_MONGO_USERNAME \
  -e MONGO_INITDB_ROOT_PASSWORD=$MR_MONGO_PASSWORD \
  -p $MR_MONGO_PORT:27017 \
  mongo
fi

npm run dev

  
