#!/bin/bash
. ./env.list

docker run -d --name $MR_NAME-dev-mongo --rm \
  --mount type=bind,src=$MR_MONGO_DATA_PATH,dst=/data/db \
  -e MONGO_INITDB_ROOT_USERNAME=$MR_MONGO_USERNAME \
  -e MONGO_INITDB_ROOT_PASSWORD=$MR_MONGO_PASSWORD \
  -p $MR_MONGO_PORT:27017 \
  mongo
  
